### ISSUE TITLE
Can't register webhooks to Pub Sub as docs prescribe

### ISSUE THREAD

**Issue by emilbonnek** [Shopify/shopify-node-api#228]
# Issue summary

When using `Webhooks.Registry.Register()` it should be possible to register a webhook for Pub Sub.
**From docs:**
> For Pub/Sub, the path must be of the form pubsub://[PROJECT-ID]:[PUB-SUB-TOPIC-ID]. For example, if you created a topic with id red in the project blue, then the value of path would be pubsub://blue:red

However it only registers a webhook for the apps url + the path value.
If the app has url: _123.ngrok.io_ and the above value for path is used it registers _123.ngrok.iopubsub//blue:red_.

Obviously the above is wrong as it is just a concat of the url and the Pub Sub address.

## Expected behavior

It should register the event for a Pub Sub topic as described in the docs.

## Actual behavior

It registers a webhook to a url. 

## Steps to reproduce the problem

(using the latest version of shopify cli 2.1.0 to get started)
1. run `shopify node create`
2. in server/server.js add the following on line 53:
`await Shopify.Webhooks.Registry.register({
  shop,
  accessToken,
  path: "pubsub://blue:red",
  topic: "PRODUCTS_CREATE"
});` 
3. run app and install on dev store
4. create a product on dev store

Go to partner dashboard and confirm there are failed webhook deliveries. You can see that they have been attempted delivered to the address as described before.

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by emilbonnek** [comment]
Hi @arsnl :)
Thanks for the swift response!

I looked in the repo and found the `DeliveryMethod` enum right after I posted the issue.
However, it didn't actually solve the issue for me.

I still get failed webhook deliveries to the _123.ngrok.iopubsub//blue:red_ like address after registering it with the deliveryMethod param. My GCP project name has a '-' symbol, I wondered for a second if that could be the issue.
Do you have any other suggestions?

**Comment by arsnl** [comment]
Just to be sure, after you have added the DeliveryMethod parameter, did you uninstalled then reinstalled the application on your development store? 

The store must be reauthorized to re-execute the register method so Shopify receive the new Webhook handler url (your app url, Google Pub/Sub or Amazon EventBridge).

**Comment by emilbonnek** [comment]
Yes, the app was uninstalled and reinstalled before I tried.
The register method is executed with the deliveryMethod parameter without a doubt.

Let me pass you the exact value of my path parameter. I guess ithere is no reason to be secretive about that.
`path: "pubsub://mirror-mate:Shopify"`
Maybe you can try if the parsing to Seperate GCP id and Pub Sub topic works as expected on that string?

btw. I noticed that the topic should be `"PRODUCTS_CREATE"` and not `"PRODUCTS_CREATED"`. This was a typo and not my actual problem. I fixed that and edited my original comment just in case someone stumbles into it.

**Comment by arsnl** [comment]
Ok! :) So to summarize the issue.

You've now changed the register setting for something like this;

```ts
import Shopify, { DeliveryMethod } from "@shopify/shopify-api";

// ...
await Shopify.Webhooks.Registry.register({ 
  shop, 
  accessToken, 
  path: "pubsub://mirror-mate:Shopify", 
  topic: "PRODUCTS_CREATE",
  deliveryMethod: DeliveryMethod.PubSub,
});
```

You then uninstall and reinstall your app on your development store. Then you create a product to test the Webhook but you still receive error message from Shopify telling you that the payload delivery as failed on `123.ngrok.iopubsub//mirror-mate:Shopify` (something like that).

Am I right?

Can you tell me which `API_VERSION` you are using on your application [Context](https://github.com/Shopify/shopify-node-api/blob/main/docs/getting_started.md#set-up-context)?

Also, if you go in you application setup on [Shopify Partner](https://partners.shopify.com/), what is the event version you are using for the Event subscriptions?

![Capture d’écran, le 2021-08-04 à 13 11 54](https://user-images.githubusercontent.com/763489/128225052-985d2a19-6ff7-4160-9c48-dd39d58e412c.png)

**Comment by emilbonnek** [comment]
Yes, you got everything right! :)

Everything is as the Shopify CLI generated it.
So the `API_VERSION `is `ApiVersion.October20` and the Event version is `2021-07 (latest)`

**Comment by arsnl** [comment]
Ah! I think we just found your issue! :)

Try with this `API_VERSION`, `ApiVersion.July21`.

I believe the Pub/Sub support was added in the API version July21. So you must use the July21 or later API version.

**Comment by emilbonnek** [comment]
That makes sense!
However, it seems that the Shopify CLI depends on version 1.2.1 of this library which didn't have version July21 available yet.
![Screenshot 2021-08-04 222003](https://user-images.githubusercontent.com/6923755/128249759-eeae915a-10e4-472f-bcac-71edc7d91269.jpg)

**Comment by arsnl** [comment]
Yeah, I see that! :) Haha! 😂  

I had the same experience while using the App Template provided by the CLI, I understand your pain! 

As you see, the App Template is not really up-to-date and lot of bump requests from Dependabot are still waiting since January (https://github.com/Shopify/shopify-app-node/pulls).

The best you can do for the moment is to update your packages manually one by one until you can update your version of `@shopify/shopify-api` to `^1.4.1`. I suggest you to start by `@shopify/koa-shopify-auth`.

**Comment by emilbonnek** [comment]
Yup, I just bumped up to 1.4.1 and everything is working just fine now 👍 
Thanks for the help! and also for the tips on the CLI.
